server:
  port: 9916

spring:
  application:
    name: bulletin
  data:
    mongodb:
      uri: mongodb://localhost:27017/Education_bulletin
#      uri: mongodb+srv://niyobethel:GCSsTx0qpEWjvW4z@bethel22.ycywdha.mongodb.net/EDUCATION?retryWrites=true&w=majority&appName=Bethel22

