server:
  port: 9906

spring:
  application:
    name: class-course
  data:
    mongodb:
#      uri: mongodb://localhost:27017/Education_class_course
      uri: mongodb+srv://niyobethel:GCSsTx0qpEWjvW4z@bethel22.ycywdha.mongodb.net/EDUCATION?retryWrites=true&w=majority&appName=Bethel22

