server:
  port: 9915

spring:
  application:
    name: cafeteria
  data:
    mongodb:
#      uri: mongodb://localhost:27017/EDUCATION
      uri: mongodb+srv://niyobethel:GCSsTx0qpEWjvW4z@bethel22.ycywdha.mongodb.net/EDUCATION?retryWrites=true&w=majority&appName=Bethel22

