server:
  port: 9911
spring:
  application:
    name: evaluation
  data:
    mongodb:
       uri: mongodb+srv://niyobethel:GCSsTx0qpEWjvW4z@bethel22.ycywdha.mongodb.net/EDUCATION?retryWrites=true&w=majority&appName=Bethel22
