server:
  port: 9909

spring:
  application:
    name: parent
  data:
    mongodb:
#      uri: mongodb://localhost:27017/Education_parent
      uri: mongodb+srv://niyobethel:GCSsTx0qpEWjvW4z@bethel22.ycywdha.mongodb.net/EDUCATION?retryWrites=true&w=majority&appName=Bethel22
